version: '3.1'

services:
  rust:
    build:
      context: .
      dockerfile: mold.dockerfile
      args:
        - OS_UID
        - OS_GID
        - OS_USERNAME
        - OS_GROUPNAME
    volumes:
      - "../:/home/${USER}/apps:rw"
    networks:
      - dn-rust
    working_dir: /home/${USER}/apps
    tty: true

networks:
  dn-rust: